---
- name: Manage Helm Charts
  hosts: localhost
  connection: local
  gather_facts: no 

  vars:
    kubeconfig_path: "~/.kube/config"
    helm_repos:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
      - name: stable
        url: https://charts.helm.sh/stable
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
